AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    myfunc
    Describe what this function does here

Resources:
    MyFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: myfunc/
            Handler: app.lambda_handler
            Runtime: python3.7
            MemorySize: 128
            Timeout: 3
            Environment: 
                Variables:
                    PARAM1: VALUE
            Events:
                Calculate:
                    Type: Api 
                    Properties:
                        Path: /calc/{proxy+}
                        Method: ANY

Outputs:

    MyFunctionApi:
      Description: "API Gateway endpoint URL for Prod stage for this function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/calc/"

    MyFunction:
      Description: "This Lambda Function ARN"
      Value: !GetAtt MyFunction.Arn

    MyFunctionIamRole:
      Description: "Implicit IAM Role created for this function"
      Value: !GetAtt MyFunctionRole.Arn
